---

# This playbook deploys the whole application stack in this site.  

- name: Apply common configuration to all nodes
  hosts: all

  roles:
    - {role: application, application_installpath: /var/www/wiki}
